export function createAnnotationState() {
  return {
    store: { threads: [], easyEdits: [] },
    selectedElement: null,
    selectedElementPath: '',
    selectedElementRef: '',
    activeThreadId: '',
    activeMessageId: '',
    activeEditId: '',
    mediumEditorLoadPromise: null,
    latestSavedEditsUpdatedAt: null,
    latestSelfSavedEditsHash: '',
    latestSelfSavedEditsCount: 0,
    pendingRemoteEditsSnapshot: null,
    hasLoadedInitialEditsSnapshot: false,
    isCollabComplete: false,
    latestRemoteCollabSnapshot: null,
    floatingUiFrameId: null,
    threadTargetCache: new Map(),
    mainClickHandler: null,
    layerClickHandler: null,
    panelClickHandler: null,
    panelInputHandler: null,
    panelKeydownHandler: null,
    panelFocusoutHandler: null,
    panelChangeHandler: null,
    inlineToggleChangeHandler: null,
    inlineCommentsToggleChangeHandler: null,
    inlineAssetsToggleChangeHandler: null,
    documentClickHandler: null,
    windowResizeHandler: null,
    mainScrollHandler: null,
    canvasRefreshBarClickHandler: null,
  };
}

export function createAnnotationUI() {
  return {
    mainEl: null,
    layerEl: null,
    popupEl: null,
    panelEl: null,
    panelListEl: null,
    canvasRefreshBarEl: null,
    inlineToggleEl: null,
    inlineCommentsToggleEl: null,
    inlineAssetsToggleEl: null,
    inlineMode: false,
    annotationMode: 'comments',
    mediumEditorInstance: null,
    editableElements: [],
    editableImages: [],
    inlineElementSnapshot: new Map(),
    inlineImageAltSnapshot: new Map(),
    inlineBlurHandlers: new Map(),
    inlineSelectedImageEl: null,
    inlineImageSelectHandler: null,
    inlineAltPopupEl: null,
    inlineAltOutsideClickHandler: null,
  };
}
