export function createAnnotationState() {
  return {
    store: { threads: [], easyEdits: [] },
    selectedElement: null,
    selectedElementPath: '',
    selectedElementRef: '',
    activeThreadId: '',
    activeMessageId: '',
    activeEditId: '',
    mediumEditorLoadPromise: null,
    commentThreadPollId: null,
    floatingUiFrameId: null,
    threadTargetCache: new Map(),
    mainClickHandler: null,
    layerClickHandler: null,
    panelClickHandler: null,
    panelInputHandler: null,
    panelKeydownHandler: null,
    panelChangeHandler: null,
    inlineToggleChangeHandler: null,
    inlineCommentsToggleChangeHandler: null,
    inlineAssetsToggleChangeHandler: null,
    documentClickHandler: null,
    documentVisibilityHandler: null,
    windowResizeHandler: null,
    mainScrollHandler: null,
    daCollabClient: null,
    daCollabStatus: 'idle',
    daCollabStatusUnsubscribe: null,
    daProsemirrorBridge: null,
    daSourceHtmlBase: '',
    daLastMirroredHtml: '',
    daMirrorTimeoutId: 0,
    daMirrorInFlight: false,
    daMirrorQueued: false,
    realtimeTargetRegistry: new Map(),
    realtimeDirtyTargetKeys: new Set(),
    realtimeApplyingTargetKeys: new Set(),
    realtimeTargetObservers: new Map(),
    realtimeTargetsMapUnsubscribe: null,
    realtimeEditingInitialized: false,
    realtimeEditingAvailable: false,
  };
}

export function createAnnotationUI() {
  return {
    mainEl: null,
    layerEl: null,
    popupEl: null,
    panelEl: null,
    panelListEl: null,
    inlineToggleEl: null,
    inlineCommentsToggleEl: null,
    inlineAssetsToggleEl: null,
    inlineMode: false,
    annotationMode: 'comments',
    mediumEditorInstance: null,
    editableElements: [],
    editableImages: [],
    inlineBlurHandlers: new Map(),
    inlineSelectedImageEl: null,
    inlineImageSelectHandler: null,
    inlineAltPopupEl: null,
    inlineAltOutsideClickHandler: null,
    inlineTargetSelectionHandler: null,
    inlineEditorOverlayEl: null,
    inlineEditorTitleEl: null,
    inlineEditorMetaEl: null,
    inlineEditorSurfaceEl: null,
    inlineEditorTextareaEl: null,
    inlineEditorTargetKey: '',
  };
}
